# Generated by Django 5.1.5 on 2025-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=10),
        ),
    ]
