# Generated by Django 5.1.5 on 2025-02-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_resturant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tables', to='resturant.restaurant'),
        ),
    ]
