# Generated by Django 5.1.5 on 2025-02-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_restaurant_alter_table_resturant'),
        ('user', '0003_remove_user_resturant_user_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resturant',
        ),
    ]
