# Generated by Django 5.1.5 on 2025-02-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_delete_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
    ]
