# Generated by Django 5.1.5 on 2025-02-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_restaurant_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
    ]
