# Generated by Django 5.1.5 on 2025-02-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_remove_restaurant_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='resturant',
            new_name='restaurant',
        ),
    ]
