# Generated by Django 5.1.5 on 2025-02-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_resturant_user_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
    ]
