# Generated by Django 5.1.5 on 2025-02-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_resturant_admin',
            new_name='is_restaurant_admin',
        ),
    ]
