# Generated by Django 5.1.5 on 2025-02-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_delete_resturant'),
        ('user', '0005_rename_is_resturant_admin_user_is_restaurant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resturant.restaurant'),
        ),
    ]
