# Generated by Django 5.1.5 on 2025-02-06 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_remove_restaurant_admin'),
        ('user', '0006_user_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resturant.restaurant'),
        ),
    ]
