# Generated by Django 5.1.5 on 2025-02-10 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_restaurant'),
        ('resturant', '0009_restaurant_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('customer', 'date', 'restaurant')},
        ),
    ]
